title: "My Website"
description: "Welcome to my website and blog."
author: "me"

url: "https://sarahrashed.com/"
baseurl: "/sarah-website"

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap